name: CI - Build, Test, and Publish Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build & (optionally) test the .NET app
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore/Build/Test
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          # If you add tests later, keep this line. If no tests yet, it's harmless:
          dotnet test --configuration Release --no-build

      # Build and push Docker image to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/arbox-ems
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
